In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score

In [18]:
ds=pd.read_csv("breast_cancer.csv")
ds.head()
ds.columns

Index(['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [5]:
x=ds.iloc[:,1:-1].values
y=ds.iloc[:,-1].values
y=y.reshape(len(y),1)

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)

[[ 5  1  2 ...  3  1  1]
 [10  4  3 ... 10  1  1]
 [ 5  3  5 ...  5  3  1]
 ...
 [10  6  4 ...  3  2  3]
 [ 2  1  1 ...  3  1  1]
 [ 5  4  4 ...  5  6  1]]


In [11]:
lr=LogisticRegression(random_state=1,solver="lbfgs")
lr.fit(x_train,y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=1, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
y_pred=lr.predict(x_test)
print(y_pred)

[2 2 2 4 2 4 2 2 4 4 2 2 4 2 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 4 4 2 4 2
 2 4 4 4 2 2 4 2 2 2 2 4 2 2 2 4 2 2 2 4 2 2 2 2 4 2 2 2 4 2 4 4 2 2 4 2 2
 4 2 2 2 2 2 2 2 4 2 4 4 2 2 2 4 2 2 4 2 2 4 4 2 2 4 2 2 4 4 2 2 2 2 4 2 4
 4 2 4 2 4 2 2 2 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2 2 2 4]


In [15]:
cm=confusion_matrix(y_pred,y_test)
print(cm)

[[90  2]
 [ 0 45]]


In [16]:
accuracy_score(y_pred,y_test)

0.9854014598540146