In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds=pd.read_csv("Iris.csv")
ds.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
x=ds.iloc[:,1:5].values
y=ds.iloc[:,-1].values
print(x)
y=y.reshape(len(y),1)
print(y)
print(type(y))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
for i in y:
    print(i)
    print(type(i))

['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>
['Iris-setosa']
<class 'numpy.ndarray'>


In [5]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
y=l.fit_transform(y)
#y=y.reshape(len(y),1)
print(y)
print(type(y))
a=[]
for i in y:
    a.append(int(i))
print(a)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
a=[]
for i in y:
    a.append(int(i))
print(a)
print(type(a))
b=np.array(a)
print(b)
print(type(b))
b=b.reshape(len(b),1)
print(b)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
<class 'list'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,b,test_size=0.25,random_state=1)
print(y_train)
y_train=y_train.reshape(len(y_train),1)
print(type(y_train))
print(np.ndim(y_train))

[[1]
 [2]
 [2]
 [0]
 [2]
 [2]
 [1]
 [2]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [0]
 [2]
 [2]
 [0]
 [0]
 [2]
 [0]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [0]
 [1]
 [1]
 [2]
 [1]
 [2]
 [1]
 [0]
 [0]
 [0]
 [2]
 [0]
 [1]
 [2]
 [2]
 [0]
 [0]
 [1]
 [0]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [2]
 [2]
 [2]
 [0]
 [0]
 [1]
 [0]
 [2]
 [0]
 [2]
 [2]
 [0]
 [2]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [2]
 [0]
 [0]
 [2]
 [1]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [0]]
<class 'numpy.ndarray'>
2


In [8]:
def evaluate_on_test_data(model=None):
    predictions=model.predict(x_test)
    correct_classifications=0
    for i in range(len(y_test)):
        if predictions[i]==y_test[i]:
            correct_classifications+=1
    accuracy=100 * (correct_classifications)/len(y_test)
    return accuracy

In [11]:
from sklearn import svm
kernels=("linear","poly","rbf")
accuracies=[]
for index,kernel in enumerate(kernels):
    model=svm.SVC(kernel=kernel,gamma="auto")
    model.fit(x_train,y_train.ravel())
    acc = evaluate_on_test_data(model)
    accuracies.append(float(acc))
    print(" {} % accuracy obtained with kernel ={}".format(acc,kernel))

 100.0 % accuracy obtained with kernel =linear
 100.0 % accuracy obtained with kernel =poly
 97.36842105263158 % accuracy obtained with kernel =rbf


In [ ]:
svc=svm.SVC(kernel="linear",gamma="auto").fit(x_train,y_train.ravel())
rbf_svc=svm.SVC(kernel="rbf",gamma=0.7).fit(x_train,y_train.ravel())
poly_svc=svm.SVC(kernel="poly",degree=3,gamma="auto").fit(x_train,y_train.ravel())

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
for index,kernel in enumerate(kernels):
    model=svm.SVC(kernel=kernel,gamma="auto")
    model.fit(x_train,y_train.ravel())
    acc=accuracy_score(model.predict(x_train),y_train)
    accuracies.append(float(acc))
    print(" {} % accuracy obtained with kernel ={}".format(100*acc,kernel))

 98.21428571428571 % accuracy obtained with kernel =linear
 97.32142857142857 % accuracy obtained with kernel =poly
 98.21428571428571 % accuracy obtained with kernel =rbf
